### ISSUE TITLE
What happened to release > 5.2.8?

### ISSUE THREAD

**Issue by fcolista** [halturin/multitail#5]
Hello.
I'm the maintainer of multitail for Alpine Linux and we have this package in community release since 2016 [1]
Suddenly the versions > 5.2.8 disappeared without notice.

Can you please explain what happened?

Downgrade the version is a nightmare, for all the versions released, as you can understand.

Maybe you can tag a newer release here on GitHub?

Thanks.

.: Francesco

[1] https://pkgs.alpinelinux.org/packages?name=multitail&branch=v3.5

**Comment by halturin** [comment]
Hello

thanks for the report. I'm not the original author of this project (have mentioned it in the README file), but I can create a tag for that. Let it be 5.3.0 if you don't mind.

**Comment by fcolista** [comment]
I don't think it can be minor of the latest version (6.5.0) shipped.

**Comment by fcolista** [comment]
@halturin thank you very much. This will make packagers happy ;-)
